// Copyright 2026, University of Colorado Boulder

/**
 * Structured food and exercise data ported from the legacy Java simulation's properties files.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */

import EatingExerciseAndEnergyUnits from './EatingExerciseAndEnergyUnits.js';

const FOOD_ITEMS = [
  { key: 'balanced-daily-diet', calories: 2000, lipidGrams: 600 / 9, carbohydrateGrams: 200, proteinGrams: 150, image: 'food-pyramid.png' },
  { key: 'serving-corn-flakes', calories: 100, lipidGrams: 0, carbohydrateGrams: 24, proteinGrams: 2, image: 'corn_flakes.png' },
  { key: 'cola-12-oz', calories: 145.5, lipidGrams: 0, carbohydrateGrams: 40.5, proteinGrams: 0, image: 'cola.png' },
  { key: 'slice-pizza', calories: 310, lipidGrams: 14, carbohydrateGrams: 31, proteinGrams: 14, image: 'pizza.png' },
  { key: 'large-fast-food-value-meal', calories: 1320, lipidGrams: 51, carbohydrateGrams: 189, proteinGrams: 35, image: 'fast-food.png' },
  { key: 'taco', calories: 160, lipidGrams: 10, carbohydrateGrams: 11, proteinGrams: 7, image: 'taco.png' },
  { key: 'burrito', calories: 378, lipidGrams: 11.7, carbohydrateGrams: 55, proteinGrams: 15, image: 'burrito.png' },
  { key: 'entire-pizza-12', calories: 1446, lipidGrams: 55.6, carbohydrateGrams: 158.6, proteinGrams: 80.9, image: 'pizza_pie.png' },
  { key: 'peanut-butter-and-jelly-sandwich', calories: 331.28, lipidGrams: 14.55, carbohydrateGrams: 41.64, proteinGrams: 10.66, image: 'pbj.png' },
  { key: 'sub-sandwich', calories: 456, lipidGrams: 18.6, carbohydrateGrams: 51, proteinGrams: 21.8, image: 'sub.png' },
  { key: 'hot-dog-with-bun', calories: 234, lipidGrams: 16, carbohydrateGrams: 15, proteinGrams: 8.4, image: 'hot_dog.png' },
  { key: 'hamburger', calories: 305, lipidGrams: 13, carbohydrateGrams: 29, proteinGrams: 16, image: 'burger.png' },
  { key: 'quarter-lb-hamburger', calories: 424, lipidGrams: 22, carbohydrateGrams: 33, proteinGrams: 24, image: 'quarter_burger.png' },
  { key: 'large-fries', calories: 539, lipidGrams: 28.8, carbohydrateGrams: 63.4, proteinGrams: 6.4, image: 'fries.png' },
  { key: 'salad-with-dressing', calories: 175, lipidGrams: 16, carbohydrateGrams: 6, proteinGrams: 2, image: 'salad.png' },
  { key: 'cup-strawberries', calories: 49, lipidGrams: 0.5, carbohydrateGrams: 11.7, proteinGrams: 1, image: 'strawberry.png' },
  { key: 'cup-grapefruit', calories: 97, lipidGrams: 0.3, carbohydrateGrams: 24.5, proteinGrams: 1.8, image: 'grapefruit.png' },
  { key: 'apple', calories: 65, lipidGrams: 0.2, carbohydrateGrams: 17.3, proteinGrams: 0.3, image: 'apple.png' },
  { key: 'banana', calories: 110, lipidGrams: 0, carbohydrateGrams: 29, proteinGrams: 1, image: 'banana.png' },
  { key: 'grapes', calories: 62, lipidGrams: 0, carbohydrateGrams: 16, proteinGrams: 0.5, image: 'grapes.png' },
  { key: 'cup-yogurt-low-fat-plain', calories: 154, lipidGrams: 3.8, carbohydrateGrams: 17.2, proteinGrams: 12.9, image: 'yogurt.png' },
  { key: 'cup-yogurt-flavored', calories: 243, lipidGrams: 2.8, carbohydrateGrams: 45.7, proteinGrams: 9.8, image: 'yogurt_flavored.png' },
  { key: 'cup-milk-whole', calories: 150, lipidGrams: 8.2, carbohydrateGrams: 11, proteinGrams: 8, image: 'milk.png' },
  { key: 'cup-milk-2', calories: 122, lipidGrams: 4.8, carbohydrateGrams: 11.4, proteinGrams: 8.1, image: 'milk_2.png' },
  { key: 'cup-milk-skim', calories: 86, lipidGrams: 0.4, carbohydrateGrams: 11.9, proteinGrams: 8.4, image: 'milk_skim.png' },
  { key: 'apple-juice-1-cup-248-g', calories: 117, lipidGrams: 0.3, carbohydrateGrams: 29, proteinGrams: 0.1, image: 'apple_juice.png' },
  { key: 'orange-juice-not-concentrate-8-oz', calories: 110, lipidGrams: 0, carbohydrateGrams: 25, proteinGrams: 1, image: 'orange_juice.png' },
  { key: 'ice-tea-8-fl-oz', calories: 86, lipidGrams: 0, carbohydrateGrams: 21.8, proteinGrams: 0, image: 'iced_tea.png' },
  { key: 'lemonade-8-fl-oz', calories: 99, lipidGrams: 0.1, carbohydrateGrams: 25.8, proteinGrams: 0.2, image: 'lemonade.png' },
  { key: 'diet-cola-12-oz', calories: 1.5, lipidGrams: 0, carbohydrateGrams: 0.15, proteinGrams: 0, image: 'diet_cola.png' },
  { key: 'hot-chocolate-whole-milk', calories: 330, lipidGrams: 18, carbohydrateGrams: 33, proteinGrams: 11.3, image: 'hot_chocolate.png' },
  { key: 'latte-with-whole-milk', calories: 180, lipidGrams: 9, carbohydrateGrams: 14, proteinGrams: 10, image: 'latte.png' },
  { key: 'large-sugary-blended-coffee-drink', calories: 590, lipidGrams: 22, carbohydrateGrams: 96, proteinGrams: 9, image: 'coffee.png' },
  { key: 'large-milkshake', calories: 1500, lipidGrams: 70, carbohydrateGrams: 197, proteinGrams: 23, image: 'large_milkshake.png' },
  { key: 'milkshake', calories: 990, lipidGrams: 40, carbohydrateGrams: 149, proteinGrams: 20, image: 'milkshake.png' },
  { key: 'baked-potato-in-skin-with-salt', calories: 278, lipidGrams: 0.4, carbohydrateGrams: 63.2, proteinGrams: 7.5, image: 'potato.png' },
  { key: 'half-cup-sweet-yellow-corn', calories: 66, lipidGrams: 0.9, carbohydrateGrams: 15, proteinGrams: 2.5, image: 'corn.png' },
  { key: 'half-cup-cauliflower-boiled', calories: 14, lipidGrams: 0.3, carbohydrateGrams: 2.5, proteinGrams: 1.1, image: 'cauliflower.png' },
  { key: 'half-cup-carrots-chopped', calories: 26, lipidGrams: 0.15, carbohydrateGrams: 6.15, proteinGrams: 0.6, image: 'carrot.png' },
  { key: 'half-cup-broccoli-cooked', calories: 27, lipidGrams: 0.3, carbohydrateGrams: 5.6, proteinGrams: 1.9, image: 'broccoli.png' },
  { key: 'serving-honey-ham-100-g', calories: 122, lipidGrams: 2.4, carbohydrateGrams: 7.3, proteinGrams: 17.9, image: 'ham.png' },
  { key: 'pork-chop-3-oz-84-g', calories: 160, lipidGrams: 6, carbohydrateGrams: 0, proteinGrams: 26, image: 'pork_chop.png' },
  { key: 'chicken', calories: 184, lipidGrams: 4, carbohydrateGrams: 0, proteinGrams: 36, image: 'chicken.png' },
  { key: 'beef', calories: 160, lipidGrams: 8, carbohydrateGrams: 0, proteinGrams: 24, image: 'beef.png' },
  { key: 'set-of-3-slices-of-bacon', calories: 103, lipidGrams: 7.9, carbohydrateGrams: 0.3, proteinGrams: 7, image: 'bacon.png' },
  { key: 'small-bag-potato-chips', calories: 155, lipidGrams: 10.6, carbohydrateGrams: 14.1, proteinGrams: 1.9, image: 'potato_chips.png' },
  { key: 'quarter-cup-mixed-nuts-with-peanuts', calories: 200, lipidGrams: 15.555, carbohydrateGrams: 10, proteinGrams: 5, image: 'cashews.png' },
  { key: 'serving-cream-filled-cookies', calories: 160, lipidGrams: 7, carbohydrateGrams: 25, proteinGrams: 2, image: 'cream_filled_cookie.png' },
  { key: 'candy-bar', calories: 218, lipidGrams: 10.9, carbohydrateGrams: 27.1, proteinGrams: 2.7, image: 'candy_bar.png' },
  { key: 'banana-split', calories: 894, lipidGrams: 43, carbohydrateGrams: 121, proteinGrams: 15, image: 'bananasplit.png' },
  { key: 'rice-cup', calories: 205, lipidGrams: 0, carbohydrateGrams: 45, proteinGrams: 4, image: 'rice.png' },
  { key: 'bowl-of-pasta', calories: 262, lipidGrams: 3.7, carbohydrateGrams: 47.6, proteinGrams: 8.6, image: 'pasta.png' },
  { key: 'slice-of-bread', calories: 65, lipidGrams: 1, carbohydrateGrams: 12.1, proteinGrams: 2.6, image: 'bread_slice.png' },
  { key: 'bagel', calories: 354, lipidGrams: 2.1, carbohydrateGrams: 70.2, proteinGrams: 13.7, image: 'bagel.png' },
  { key: 'pancakes', calories: 148, lipidGrams: 2, carbohydrateGrams: 28, proteinGrams: 4, image: 'pancakes.png' },
  { key: 'syrup', calories: 96, lipidGrams: 0, carbohydrateGrams: 24, proteinGrams: 0, image: 'syrup.png' },
  { key: 'egg', calories: 90, lipidGrams: 7, carbohydrateGrams: 0, proteinGrams: 6, image: 'egg.png' },
  { key: 'butter', calories: 100, lipidGrams: 11, carbohydrateGrams: 0, proteinGrams: 0, image: 'stick_butter.png' },
  { key: 'cream-cheese', calories: 90, lipidGrams: 8, carbohydrateGrams: 4, proteinGrams: 1, image: 'cream_cheese.png' }
];

const EXERCISE_REFERENCE_WEIGHT_POUNDS = 160;

const EXERCISE_ITEMS = [
  { key: 'swimming-laps', referenceCaloriesPerHour: 590, weightDependent: true, image: 'swim.png' },
  { key: 'basketball', referenceCaloriesPerHour: 472, weightDependent: true, image: 'basketball.png' },
  { key: 'skateboarding', referenceCaloriesPerHour: 340, weightDependent: true, image: 'skateboarder.png' },
  { key: 'biking-to-work-or-for-leisure-10-Mph', referenceCaloriesPerHour: 272, weightDependent: true, image: 'leisure_bikers.png' },
  { key: 'jogging', referenceCaloriesPerHour: 600, weightDependent: true, image: 'jogger.png' },
  { key: 'running-stairs', referenceCaloriesPerHour: 1020, weightDependent: true, image: 'running_stairs.png' },
  { key: 'running-8-Mph-7-5-min-mile', referenceCaloriesPerHour: 979, weightDependent: true, image: 'running_1.png' },
  { key: 'running-10-Mph-6-min-mile', referenceCaloriesPerHour: 1300, weightDependent: true, image: 'running_2.png' },
  { key: 'backpacking', referenceCaloriesPerHour: 476, weightDependent: true, image: 'backpacker.png' },
  { key: 'rock-or-mountain-climbing', referenceCaloriesPerHour: 544, weightDependent: true, image: 'climber.png' },
  { key: 'snowshoeing', referenceCaloriesPerHour: 544, weightDependent: true, image: 'j0232879.png' },
  { key: 'cross-country-skiing', referenceCaloriesPerHour: 544, weightDependent: true, image: 'skier_cross_country.png' },
  { key: 'downhill-skiing-Moderate-effort', referenceCaloriesPerHour: 408, weightDependent: true, image: 'skier_downhill.png' },
  { key: 'pilates', referenceCaloriesPerHour: 238, weightDependent: true, image: 'j0429961.png' },
  { key: 'judo-Karate-Tae-Kwan-Do', referenceCaloriesPerHour: 680, weightDependent: true, image: 'judo.png' },
  { key: 'surfing', referenceCaloriesPerHour: 204, weightDependent: true, image: 'surfer_dude.png' },
  { key: 'canoeing', referenceCaloriesPerHour: 272, weightDependent: true, image: 'canoe.png' },
  { key: 'kayaking', referenceCaloriesPerHour: 340, weightDependent: true, image: 'kayaker.png' },
  { key: 'whitewater-rafting', referenceCaloriesPerHour: 340, weightDependent: false, image: 'rafting.png' },
  { key: 'rowing-crew', referenceCaloriesPerHour: 816, weightDependent: true, image: 'crew.png' },
  { key: 'horseback-riding', referenceCaloriesPerHour: 272, weightDependent: false, image: 'dude_on_horse.png' },
  { key: 'mountain-or-BMX-biking', referenceCaloriesPerHour: 578, weightDependent: true, image: 'mountain_biking.png' },
  { key: 'road-biking-10-15-Mph', referenceCaloriesPerHour: 600, weightDependent: true, image: 'road_biker.png' },
  { key: 'road-biking-racing-16-Mph-up', referenceCaloriesPerHour: 850, weightDependent: true, image: 'road_racer.png' },
  { key: 'unicycling', referenceCaloriesPerHour: 340, weightDependent: true, image: 'unicycle.png' },
  { key: 'weight-lifting-light-effort', referenceCaloriesPerHour: 204, weightDependent: true, image: 'weightlifter_nonserious.png' },
  { key: 'weight-lifting-body-building', referenceCaloriesPerHour: 408, weightDependent: true, image: 'weightlifter_serious.png' },
  { key: 'ice-skating', referenceCaloriesPerHour: 476, weightDependent: true, image: 'j0398303.png' },
  { key: 'roller-blading', referenceCaloriesPerHour: 816, weightDependent: true, image: 'j0412534.png' },
  { key: 'bowling', referenceCaloriesPerHour: 177, weightDependent: true, image: 'bowling.png' },
  { key: 'beach-volleyball', referenceCaloriesPerHour: 544, weightDependent: true, image: 'beach_volleyball.png' },
  { key: 'non-competitive-volleyball', referenceCaloriesPerHour: 204, weightDependent: true, image: 'volleyball_noncompetitive.png' },
  { key: 'playing-catch-football-or-baseball', referenceCaloriesPerHour: 170, weightDependent: true, image: 'catch.png' },
  { key: 'tennis-singles', referenceCaloriesPerHour: 476, weightDependent: true, image: 'tennis.png' },
  { key: 'tennis-doubles', referenceCaloriesPerHour: 300, weightDependent: true, image: 'tennis_doubles.png' },
  { key: 'table-tennis', referenceCaloriesPerHour: 272, weightDependent: true, image: 'table_tennis.png' },
  { key: 'squash', referenceCaloriesPerHour: 816, weightDependent: true, image: 'squash_player.png' },
  { key: 'soccer', referenceCaloriesPerHour: 476, weightDependent: true, image: 'soccer.png' },
  { key: 'lacrosse', referenceCaloriesPerHour: 544, weightDependent: true, image: 'lacrosse.png' },
  { key: 'ultimate-frisbee', referenceCaloriesPerHour: 544, weightDependent: true, image: 'ultimate.png' },
  { key: 'hockey-ice-or-field', referenceCaloriesPerHour: 544, weightDependent: true, image: 'hockey_player.png' },
  { key: 'walking-for-pleasure-like-on-a-break', referenceCaloriesPerHour: 200, weightDependent: true, image: 'walking_pleasure.png' },
  { key: 'pushing-a-stroller-with-a-kid', referenceCaloriesPerHour: 250, weightDependent: true, image: 'stroller.png' },
  { key: 'mowing-lawn', referenceCaloriesPerHour: 374, weightDependent: true, image: 'mowing_lawn.png' },
  { key: 'gardening', referenceCaloriesPerHour: 204, weightDependent: true, image: 'gardening.png' },
  { key: 'vacuuming', referenceCaloriesPerHour: 204, weightDependent: true, image: 'vacuum.png' },
  { key: 'jumping-rope', referenceCaloriesPerHour: 680, weightDependent: true, image: 'j0283852.png' },
  { key: 'dancing', referenceCaloriesPerHour: 266, weightDependent: true, image: 'dancing.png' },
  { key: 'dancing-fast-disco-folk-line-dancing', referenceCaloriesPerHour: 306, weightDependent: true, image: 'dancing_disco.png' },
  { key: 'dancing-ballet-or-modern', referenceCaloriesPerHour: 326, weightDependent: true, image: 'dancing_ballet.png' },
  { key: 'fishing-in-stream-flyfishing', referenceCaloriesPerHour: 100, weightDependent: false, image: 'fishing_rod.png' },
  { key: 'golf-walking-and-carrying-clubs', referenceCaloriesPerHour: 306, weightDependent: true, image: 'golf_walking.png' },
  { key: 'golf-using-power-cart', referenceCaloriesPerHour: 125, weightDependent: false, image: 'golf_cart.png' },
  { key: 'driving-heavy-truck', referenceCaloriesPerHour: 140, weightDependent: false, image: 'heavy_truck.png' }
];

const EatingExerciseAndEnergyData = {
  FOOD_ITEMS: Object.freeze( FOOD_ITEMS ),
  EXERCISE_ITEMS: Object.freeze( EXERCISE_ITEMS ),
  EXERCISE_REFERENCE_MASS_KILOGRAMS: EatingExerciseAndEnergyUnits.poundsToKilograms( EXERCISE_REFERENCE_WEIGHT_POUNDS )
};

export default EatingExerciseAndEnergyData;
